
// var autoIncrement = require("mongodb-autoincrement");
// exports.yourMethod = function (newData, callback) {
//     autoIncrement.getNextSequence(db, your - collection - name, function (err, autoIndex) {
//         newData.id = autoIndex;
//         //save your code with this autogenerated id
//     });
// }